### PR TITLE
Implemented two new functions

### PR DESCRIPTION
**Pull request by hlavacek**
Hello,

I've implemented two new functions for the plug-in:
eclipse.runtime.launch - runs external script
eclipse.editors.open - opens up the editor for a file

+Increased the version.
Can you merge these and create a new version of the plug-in?

### CODE REVIEW

**Comment by paulvi** [comment]
:+1:

**Comment by hlavacek** [comment]
Please do not merge it yet, I need to add some null checks - e.g. if there is no default editor for a file, it ends up on a null pointer exception.

Also I will rename the function eclipse.runtime.launch to eclipse.runtime.exec, launch seems like something with Eclipse launch configurations.

**Comment by hlavacek** [comment]
Changes done, please review and merge.

Thanks

**Comment by fornwall** [comment]
Nice! The updated plug-in has been pushed to the update site and is now available as an update.

**Comment by hlavacek** [comment]
Very nice, you've also updated the Rhino engine bundled, maybe I can try new javascript features :) thanks.

**Pull request merged**
